[package]
name = "bla"
version = "0.1.0"
edition = "2021" # Cargo edition! NOT package edition!

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
