// Call forms ported from Python, Kotlin, Swift, C#, JS/TS, Ruby and Julia (probes/function_calls*.md): each source
// with the value it shows, as `warp eval` prints it. A form that once worked stays working (batch 14 broke Python's
// `def f(a, *, b)`, which no test held)
use warp::wasm_emitter::eval;

const CASES: [(&str, &str); 271] = [
	(r#"f(a, b=2) := a + b; f(1)"#, r#"3"#),
	(r#"f(a, b=2) := a + b; f(1, 5)"#, r#"6"#),
	(r#"def f(a, b=2){a+b}; f(1)"#, r#"3"#),
	(r#"def f(a=1, b=2){a*10+b}; f()"#, r#"12"#),
	(r#"def f(a=1, b=2){a*10+b}; f(b=5)"#, r#"15"#),
	(r#"def greet(name, greeting="Hello"){greeting + " " + name}; greet("Bob")"#, r#"Hello Bob"#),
	(r#"def greet(name, greeting="Hello"){greeting + " " + name}; greet("Bob", greeting="Hi")"#, r#"Hi Bob"#),
	(r#"def f(a, b=a*2){a+b}; f(3)"#, r#"9"#),
	(r#"def f(a, b=a*2){a+b}; f(3, 1)"#, r#"4"#),
	(r#"fun area(w:int, h:int=w){w*h}; area(4)"#, r#"16"#),
	(r#"def f(a:int, b:int=2) {a+b}; f(1)"#, r#"3"#),
	(r#"def f(x:float=1.5){x*2}; f()"#, r#"3"#),
	(r#"def f(a, b, c){a*100+b*10+c}; f(1, c=3, b=2)"#, r#"123"#),
	(r#"def f(a, b, c){a*100+b*10+c}; f(c:3, a:1, b:2)"#, r#"123"#),
	(r#"def f(a, b=5, c=7){a*100+b*10+c}; f(1, c=3)"#, r#"153"#),
	(r#"def total(xs...){sum xs}; total(1,2,3)"#, r#"6"#),
	(r#"def total(...xs){sum xs}; total(1,2,3)"#, r#"6"#),
	(r#"def count(xs...){#xs}; count(1,2,3,4)"#, r#"4"#),
	(r#"def first(a, rest...){a}; first(7,8,9)"#, r#"7"#),
	(r#"def f(a, rest...){#rest}; f(7,8,9)"#, r#"2"#),
	(r#"def f(a,b,c){a+b+c}; xs=[1,2,3]; f(...xs)"#, r#"6"#),
	(r#"def f(x?){x ?? 5}; f()"#, r#"5"#),
	(r#"def f(x?){x ?? 5}; f(2)"#, r#"2"#),
	(r#"def f(x):int{return x+1}; f(1)"#, r#"2"#),
	(r#"def f(x){if x>0 {return 1}; return 2}; f(-1)"#, r#"2"#),
	(r#"def divmod(a,b){(a//b, a%b)}; q,r = divmod(7,2); q*10+r"#, r#"31"#),
	(r#"def f(a){a}; def f(a,b){a+b}; f(1)*10 + f(2,3)"#, r#"15"#),
	(r#"def f(x:int){1}; def f(x:text){2}; f(3)*10+f("a")"#, r#"12"#),
	(r#"def adder(n){ x => x + n }; add2 = adder(2); add2(3)"#, r#"5"#),
	(r#"def counter(){ n=0; ()=>{ n+=1; n } }; c=counter(); c(); c()"#, r#"2"#),
	(r#"add(a,b) := a+b; inc = add(1, _); inc(5)"#, r#"6"#),
	(r#"apply(f, x) := f(x); apply(x=>x*x, 4)"#, r#"16"#),
	(r#"twice(f, x) := f(f(x)); twice(x=>x+3, 1)"#, r#"7"#),
	(r#"map([1,2,3], x=>x*2)"#, r#"[2 4 6]"#),
	(r#"[1,2,3].map(x=>x*2)"#, r#"[2 4 6]"#),
	(r#"compose(f,g) := x => f(g(x)); h = compose(x=>x+1, x=>x*2); h(5)"#, r#"11"#),
	(r#"fact(n) := n<2 ? 1 : n*fact(n-1); fact(5)"#, r#"120"#),
	(r#"def gcd(a,b){ b==0 ? a : gcd(b, a%b) }; gcd(48,18)"#, r#"6"#),
	(r#"def ack(m,n){ if m==0 {n+1} else if n==0 {ack(m-1,1)} else {ack(m-1, ack(m, n-1))} }; ack(2,3)"#, r#"9"#),
	(r#"def even(n){ n==0 ? 1 : odd(n-1) }; def odd(n){ n==0 ? 0 : even(n-1) }; even(10)"#, r#"1"#),
	(r#"square(n) := n*n; square 3"#, r#"9"#),
	(r#"square(n) := n*n; square square 2"#, r#"16"#),
	(r#"add(a,b) := a+b; add 1 2"#, r#"3"#),
	(r#"def f(a, b=2){a+b}; f 1"#, r#"3"#),
	(r#"f(x, y=10) = x + y; f(1)"#, r#"11"#),
	(r#"def f(a, b: 2){a+b}; f(1)"#, r#"3"#),
	(r#"def f(a, b: 2){a+b}; f(1, b: 5)"#, r#"6"#),
	(r#"def counter(){ n=0; ()=>{ n=n+1; n } }; c=counter(); c(); c()"#, r#"2"#),
	(r#"def counter(){ n=0; return ()=>{ n+=1; return n } }; c=counter(); c(); c()"#, r#"2"#),
	(r#"def f(a:int, b=2) {a+b}; f(1)"#, r#"3"#),
	(r#"def f(a, b:int=2) {a+b}; f(1)"#, r#"3"#),
	(r#"def f(b:int=2) {b}; f()"#, r#"2"#),
	(r#"f(a:int, b:int=2) := a+b; f(1)"#, r#"3"#),
	(r#"def f(a:int, b:int=2) {a+b}; f(1, 4)"#, r#"5"#),
	(r#"def f(a){a}; def f(a,b){a+b}; f(2,3)"#, r#"5"#),
	(r#"def f(a,b){a+b}; def f(a){a}; f(2)"#, r#"2"#),
	(r#"mk(k) := { return x => x * k }; t = mk(3); t(4)"#, r#"12"#),
	(r#"mk(k) := x => x * k; t = mk(3); t(4)"#, r#"12"#),
	(r#"square(n) := n*n; square(square 2)"#, r#"16"#),
	(r#"def apply_n(f, n, x){ for i in 1...n { x = f(x) }; x }; apply_n(x=>x*2, 3, 1)"#, r#"8"#),
	(r#"filter([1,2,3,4], x => x%2==0)"#, r#"[2 4]"#),
	(r#"reduce([1,2,3,4], (a,b) => a+b)"#, r#"10"#),
	(r#"[1,2,3].reduce((a,b)=>a*b)"#, r#"6"#),
	(r#"fold([1,2,3], 0, (a,b)=>a+b)"#, r#"6"#),
	(r#"sorted([3,1,2], (a,b) => b-a)"#, r#"[3 2 1]"#),
	(r#"def make_adder(n) = x -> x + n; make_adder(5)(1)"#, r#"6"#),
	(r#"adder = (a, b) => a + b; adder(2, 3)"#, r#"5"#),
	(r#"mul = fn(a, b) { a * b }; mul(2, 3)"#, r#"6"#),
	(r#"f = lambda x: x * 2; f(4)"#, r#"8"#),
	(r#"sq = { |x| x * x }; sq(5)"#, r#"25"#),
	(r#"sq = x -> x * x; sq(5)"#, r#"25"#),
	(r#"(x => x + 1)(2)"#, r#"3"#),
	(r#"square(x) := x*x; def f(g){ g(2) }; f(square)"#, r#"4"#),
	(r#"square(x) := x*x; [1,2,3].map(square)"#, r#"[1 4 9]"#),
	(r#"square(x) := x*x; map([1,2,3], square)"#, r#"[1 4 9]"#),
	(r#"def f(x: int) -> int { x + 1 }; f(1)"#, r#"2"#),
	(r#"fun f(x: Int): Int = x + 1; f(1)"#, r#"2"#),
	(r#"func f(x: Int) -> Int { return x + 1 }; f(1)"#, r#"2"#),
	(r#"function f(x: number): number { return x + 1 }; f(1)"#, r#"2"#),
	(r#"int f(int x) { return x + 1; }; f(1)"#, r#"2"#),
	(r#"def sign(x){ if x < 0 { return -1 }; if x == 0 { return 0 }; 1 }; sign(-5) + sign(0) + sign(7)"#, r#"0"#),
	(r#"def first_even(xs){ for x in xs { if x % 2 == 0 { return x } }; -1 }; first_even([1,3,4,5])"#, r#"4"#),
	(r#"def fib(n){ n < 2 ? n : fib(n-1) + fib(n-2) }; fib(15)"#, r#"610"#),
	(r#"def power(b, e){ if e == 0 {1} else { b * power(b, e-1) } }; power(2, 10)"#, r#"1024"#),
	(r#"def sum_list(xs){ if #xs == 0 {0} else { xs#1 + sum_list(xs[1:]) } }; sum_list([1,2,3])"#, r#"6"#),
	(r#"def hanoi(n){ n == 0 ? 0 : 2*hanoi(n-1)+1 }; hanoi(10)"#, r#"1023"#),
	(r#"func greet(person name: String) -> String { "Hi " + name }; greet(person: "Bob")"#, r#"Hi Bob"#),
	(r#"def f(a, b) { a - b }; f(b: 1, a: 10)"#, r#"9"#),
	(r#"def twice(x) { x * 2 }; twice 21"#, r#"42"#),
	(r#"def add(a, b) { a + b }; add 1, 2"#, r#"3"#),
	(r#"def greet(name) { "hi " + name }; greet "bob""#, r#"hi bob"#),
	(r#"puts(x) := x; puts 3"#, r#"3"#),
	(r#"def f(a, b=max(a, 3)){ b }; f(1)"#, r#"3"#),
	(r#"def f(xs=[]){ #xs }; f()"#, r#"0"#),
	(r#"def f(xs=[1,2]){ #xs }; f()"#, r#"2"#),
	(r#"def f(s="a"){ s + s }; f()"#, r#"aa"#),
	(r#"def minmax(xs){ return min(xs), max(xs) }; lo, hi = minmax([3,1,2]); lo*10+hi"#, r#"13"#),
	(r#"def swap(a, b){ (b, a) }; x, y = swap(1, 2); x*10+y"#, r#"21"#),
	(r#"x = 10; def f(){ x * 2 }; f()"#, r#"20"#),
	(r#"def outer(){ y = 5; def inner(){ y + 1 }; inner() }; outer()"#, r#"6"#),
	(r#"fun f(a: Int = 1, b: Int = 2): Int { return a * b }; f(b = 5)"#, r#"5"#),
	(r#"fun f(a: Int, b: Int): Int = a + b; f(1, 2)"#, r#"3"#),
	(r#"function f(x; y=2) x*y end; f(3)"#, r#"6"#),
	(r#"function f(x; y=2) x*y end; f(3; y=4)"#, r#"12"#),
	(r#"f(x) = 2x; f(4)"#, r#"8"#),
	(r#"def f(*args): return len(args); f(1,2,3)"#, r#"3"#),
	(r#"def f(**kw): return kw["a"]; f(a=1)"#, r#"1"#),
	(r#"int Add(int a, int b = 2) { return a + b; }; Add(1)"#, r#"3"#),
	(r#"static int Add(int a, int b) => a + b; Add(1, 2)"#, r#"3"#),
	(r#"const f = (a, b = 2) => a * b; f(4)"#, r#"8"#),
	(r#"let f = (a: number): number => a * 2; f(4)"#, r#"8"#),
	(r#"def f(a, b: 2) a * b end; f(3)"#, r#"6"#),
	(r#"def f(a, b: 2) a * b end; f(3, b: 5)"#, r#"15"#),
	(r#"func f(_ a: Int, times b: Int) -> Int { a * b }; f(3, times: 4)"#, r#"12"#),
	(r#"[1,2,3].forEach { print(it) }"#, r#"ø"#), // prints 1 2 3
	(r#"xs = [1,2,3]; xs.each { |x| print x }"#, r#"ø"#), // prints 1 2 3
	(r#"def twice(f, x){ f(f(x)) }; twice(x => x + 1, 5)"#, r#"7"#),
	(r#"compose = (f, g) => x => f(g(x)); h = compose(x => x + 1, x => x * 2); h(5)"#, r#"11"#),
	(r#"add = a => b => a + b; add(1)(2)"#, r#"3"#),
	(r#"fun total(vararg xs: Int): Int = xs.sum(); total(1, 2, 3)"#, r#"6"#),
	(r#"int Total(params int[] xs) { return xs.sum(); }; Total(1, 2, 3)"#, r#"6"#),
	(r#"def f(a, *, b): return a + b; f(1, b=2)"#, r#"3"#),
	(r#"f(x) = x^2; f.([1,2,3])"#, r#"[1 4 9]"#),
	(r#"map(x -> x * 2, [1,2,3])"#, r#"[2 4 6]"#),
	(r#"function f(a, b = a * 2) { return a + b }; f(3)"#, r#"9"#),
	(r#"def fact(n, acc=1){ if n <= 1 { acc } else { fact(n - 1, acc * n) } }; fact(5)"#, r#"120"#),
	(r#"add = (a) => (b) => a + b; add(2)(3)"#, r#"5"#),
	(r#"def apply(f, *args): return f(*args); apply((a, b) => a * b, 3, 4)"#, r#"12"#),
	(r#"func swapped(_ a: Int, _ b: Int) -> (Int, Int) { return (b, a) }; swapped(1, 2)"#, r#"(2 1)"#),
	(r#"def f(x): return x * 2; list(map(f, [1, 2, 3]))"#, r#"[2 4 6]"#),
	(r#"square = lambda x: x ** 2; square(5)"#, r#"25"#),
	(r#"const inc = x => x + 1; [1,2,3].map(inc)"#, r#"[2 3 4]"#),
	(r#"fn add(a: i32, b: i32) -> i32 { a + b }; add(2, 3)"#, r#"5"#),
	(r#"def greet(name="World"): return "Hello " + name; greet()"#, r#"Hello World"#),
	(r#"def f(n){ return n if n < 2 else f(n-1) + f(n-2) }; f(10)"#, r#"55"#),
	(r#"max(3, 7)"#, r#"7"#),
	(r#"let twice x = x * 2 in twice 4"#, r#"8"#),
	(r#"func divmod(a, b int) (int, int) { return a / b, a % b }; q, r := divmod(7, 2); q * 10 + r"#, r#"31"#),
	(r#"function add(a, b) return a + b end; add(1, 2)"#, r#"3"#),
	(r#"function f($a) { return $a * 2; }; f(4)"#, r#"8"#),
	(r#"int twice(int x) => x * 2; twice(4)"#, r#"8"#),
	(r#"def twice(x: Int): Int = x * 2; twice(4)"#, r#"8"#),
	(r#"fun f(a: Int, b: Int = 2) = a * b; f(b = 3, a = 4)"#, r#"12"#),
	(r#"[1,2,3].map { $0 * 2 }"#, r#"[2 4 6]"#),
	(r#"def f(a, b = 2) a + b end; f(1)"#, r#"3"#),
	(r#"(function(){ return 5 })()"#, r#"5"#),
	(r#"(() => 7)()"#, r#"7"#),
	(r#"(lambda x: x + 1)(2)"#, r#"3"#),
	(r#"let xs = [1,2,3]; xs.reduce(0, +)"#, r#"6"#),
	(r#"[x * 2 for x in [1, 2, 3] if x > 1]"#, r#"[4 6]"#),
	(r#"twice x = x * 2; twice 4"#, r#"8"#),
	(r#"add a b = a + b; add 1 2"#, r#"3"#),
	(r#"twice x = x * 2
twice 4"#, r#"8"#),
	(r#"int x = 3; x"#, r#"3"#),
	(r#"number n = 2; n + n"#, r#"4"#),
	(r#"f <- function(x) x * 2; f(4)"#, r#"8"#),
	(r#"f = function(x) x * 2; f(4)"#, r#"8"#),
	(r#"add = function(a, b) { a + b }; add(1, 2)"#, r#"3"#),
	(r#"square = function(x) x * x; square [1 2 3]"#, r#"[1 4 9]"#),
	(r#"x = -5; x < -3 ? 1 : 2"#, r#"1"#),
	(r#"const f = ({a, b}) => a + b; f({a: 1, b: 2})"#, r#"3"#),
	(r#"area = ({w, h}) => w * h; area({h: 3, w: 4})"#, r#"12"#),
	(r#"f = ({a}, k) => a * k; f({a: 5}, 2)"#, r#"10"#),
	(r#"f = fn x -> x * 2 end; f.(4)"#, r#"8"#),
	(r#"add = fn a, b -> a + b end; add.(1, 2)"#, r#"3"#),
	(r#"square = fn x -> x * x end; square [1 2 3]"#, r#"[1 4 9]"#),
	(r#"map([1, 2], fn x -> x * 10 end)"#, r#"[10 20]"#),
	(r#"f = x => x * 2; f.(4)"#, r#"8"#),
	(r#"fun add(a: Int, b: Int): Int { return a + b }; add(2, 3)"#, r#"5"#),
	(r#"fun Int.half() = this / 2; 8.half()"#, r#"4"#),
	(r#"func add(_ a: Int, to b: Int) -> Int { a + b }; add(1, to: 2)"#, r#"3"#),
	(r#"static int Add(int a, int b) => a + b; Add(2, 3)"#, r#"5"#),
	(r#"Func<int, int> sq = x => x * x; sq(6)"#, r#"36"#),
	(r#"const add = (a: number, b: number): number => a + b; add(1, 2)"#, r#"3"#),
	(r#"function add(a, b = 10) { return a + b }; add(1)"#, r#"11"#),
	(r#"def add(a, b) = a + b; add(1, 2)"#, r#"3"#),
	(r#"add(x, y) = x + y; add(2, 3)"#, r#"5"#),
	(r#"sq(x) = x^2; sq.([1, 2, 3])"#, r#"[1 4 9]"#),
	(r#"int add(int a, int b) => a + b; add(1, 2)"#, r#"3"#),
	(r#"proc add(a, b: int): int = a + b; add(1, 2)"#, r#"3"#),
	(r#"fn add(a: i32, b: i32) -> i32 { a + b }; add(1, 2)"#, r#"3"#),
	(r#"def add(a: Int, b: Int) = a + b; add(1, 2)"#, r#"3"#),
	(r#"square x := x * x; square [1 2 3]"#, r#"[1 4 9]"#),
	(r#"square x := x * x; xs = [1, 2]; square all xs"#, r#"[1 4]"#),
	(r#"max(1, 5, 3)"#, r#"5"#),
	(r#"f = (x) -> x + 1; f(1)"#, r#"2"#),
	(r#"val sq = { x: Int -> x * x }; sq(5)"#, r#"25"#),
	(r#"add = { a: Int, b: Int -> a + b }; add(1, 2)"#, r#"3"#),
	(r#"add = { a, b -> a + b }; add(1, 2)"#, r#"3"#),
	(r#"let sq = { (x: Int) -> Int in x * x }; sq(4)"#, r#"16"#),
	(r#"sq = ->(x) { x * x }; sq.(3)"#, r#"9"#),
	(r#"add = ->(a, b) { a + b }; add.(1, 2)"#, r#"3"#),
	(r#"f = -> { 42 }; f.call"#, r#"42"#),
	(r#"[1,2].map(->(x) { x + 1 })"#, r#"[2 3]"#),
	(r#"sq = lambda { |x| x * x }; sq.call(3)"#, r#"9"#),
	(r#"add = proc { |a, b| a + b }; add.call(1, 2)"#, r#"3"#),
	(r#"listOf(1, 2, 3).map { it * 2 }"#, r#"[2 4 6]"#),
	(r#"arrayOf(1, 2).size"#, r#"2"#),
	(r#"def listOf(a, b){ a * b }; listOf(2, 3)"#, r#"6"#),
	(r#"local function add(a, b) return a + b end; add(1, 2)"#, r#"3"#),
	(r#"local x = 3; x"#, r#"3"#),
	(r#"def sq(x : Int) : Int; x * x; end; sq(3)"#, r#"9"#),
	(r#"fun Int.twice() = this * 2; 3.twice()"#, r#"6"#),
	(r#"class Adder { k: int; def call(x) { x + k } }; a = Adder(k: 2); a.call(1)"#, r#"3"#),
	(r#"int sq(int x) => x * x; sq(5)"#, r#"25"#),
	(r#"let sq x = x * x; sq 6"#, r#"36"#),
	(r#"let add a b = a + b; add 2 3"#, r#"5"#),
	(r#"def f(a, *, b): return a * b; f(2, b=5)"#, r#"10"#),
	(r#"def f(*args): return len(args); f(1, 2, 3)"#, r#"3"#),
	(r#"def fact(n) = n <= 1 ? 1 : n * fact(n - 1); fact(5)"#, r#"120"#),
	(r#"fact(n) = n <= 1 ? 1 : n * fact(n - 1); fact(5)"#, r#"120"#),
	(r#"compose = (f, g) => x => f(g(x)); inc = x => x + 1; dbl = x => x * 2; compose(inc, dbl)(5)"#, r#"11"#),
	(r#"apply = (f, x) => f(x); apply(x => x * 3, 4)"#, r#"12"#),
	(r#"[1, 2, 3].map(x => x * x).filter(x => x > 1)"#, r#"[4 9]"#),
	(r#"[1, 2, 3].reduce((a, b) => a + b)"#, r#"6"#),
	(r#"square x := x * x; sum square [1 2 3]"#, r#"14"#),
	(r#"func greet(name: String = "you") -> String { "hi \(name)" }; greet()"#, r#"hi you"#),
	(r#"xs = [3, 1, 2]; xs.sort()"#, r#"[1 2 3]"#),
	(r#"[3, 1, 2].sort()"#, r#"[1 2 3]"#),
	(r#"def greet(name: str = "you") -> str: return f"hi {name}"; greet()"#, r#"hi you"#),
	(r#"name = "Bo"; f"hi {name}, {1 + 1}""#, r#"hi Bo, 2"#),
	(r#"f"{{x}}""#, r#"{x}"#),
	(r#"def f(x){ x * 2 }; f"{f(2)}""#, r#"4"#),
	(r#"def sq(x){ x*x }; def g(n) { return sq n }; g(3)"#, r#"9"#),
	(r#"square x := x*x; n = 3; return square n"#, r#"9"#),
	(r#"$sq = fn($x) => $x * $x; $sq(4)"#, r#"16"#),
	(r#"var sq = (int x) => x * x; sq(3)"#, r#"9"#),
	(r#"add = (int a, int b) => a + b; add(1, 2)"#, r#"3"#),
	(r#"f = (x y) => x + y; f(1, 2)"#, r#"3"#),
	(r#"func total(_ xs: Int...) -> Int { xs.reduce(0, +) }; total(1, 2, 3)"#, r#"6"#),
	(r#"def f(a, *xs: int){ a * xs.sum() }; f(2, 1, 2)"#, r#"6"#),
	(r#"const add = (a, b = a * 2) => a + b; add(3)"#, r#"9"#),
	(r#"def f(a, b = a * 2){ a + b }; f(3)"#, r#"9"#),
	(r#"function add(...nums) { return nums.reduce((a, b) => a + b, 0) }; add(1, 2, 3)"#, r#"6"#),
	(r#"[1, 2, 3].reduce((a, b) => a * b, 10)"#, r#"60"#),
	(r#"[1,2,3].reduce(0) { $0 + $1 }"#, r#"6"#),
	(r#"xs = [1,2,3]; xs.reduce(10) { a, b in a + b }"#, r#"16"#),
	(r#"func makeAdder(_ k: Int) { return { $0 + k } }; makeAdder(2)(3)"#, r#"5"#),
	(r#"def mk(k){ return { $0 + k } }; mk(2)(3)"#, r#"5"#),
	(r#"def mk(){ return { $0 * $1 } }; mk()(3, 4)"#, r#"12"#),
	(r#"def g(a, b){ $0 - $1 }; g(5, 2)"#, r#"3"#),
	(r#"def twice(f, x){ f(f(x)) }; twice({ $0 + 1 }, 5)"#, r#"7"#),
	(r#"func makeAdder(_ k: Int) -> (Int) -> Int { return { $0 + k } }; makeAdder(2)(3)"#, r#"5"#),
	(r#"def add(x: Int)(y: Int): Int = x + y; add(1)(2)"#, r#"3"#),
	(r#"def add(x)(y) = x + y; inc = add(1); inc(5)"#, r#"6"#),
	(r#"xs = [1,2,3]; xs.max()"#, r#"3"#),
	(r#"[1,2,3].min()"#, r#"1"#),
	(r#"static int Total(params int[] xs) => xs.Sum(); Total(1, 2, 3)"#, r#"6"#),
	(r#"xs = [1, 2, 3]; xs.Aggregate((a, b) => a * b)"#, r#"6"#),
	(r#"f(x) = 2x + 1; f(3)"#, r#"7"#),
	(r#"sq = x -> x^2; sq(4)"#, r#"16"#),
	(r#"map(x -> x * 2, [1, 2, 3])"#, r#"[2 4 6]"#),
	(r#"mk = () => ({a: 1}); mk().a"#, r#"1"#),
	(r#"const f = x => y => x + y; f(1)(2)"#, r#"3"#),
	(r#"(x -> x + 1)(2)"#, r#"3"#),
	(r#"[1, 2, 3] |> map(x -> x * 10)"#, r#"[10 20 30]"#),
	(r#"let add = |a, b| a + b; add(2, 3)"#, r#"5"#),
	(r#"square(x) := x * x; square.([1, 2, 3])"#, r#"[1 4 9]"#),
	(r#"function f(x) { return x > 0 ? "pos" : "neg" }; f(-1)"#, r#"neg"#),
	(r#"fact = n -> n <= 1 ? 1 : n * fact(n - 1); fact(5)"#, r#"120"#),
	(r#"def f(x): return "pos" if x > 0 else "neg"; f(1)"#, r#"pos"#),
	(r#"def f(x): return "pos" if x > 0 else "neg"; f(-1)"#, r#"neg"#),
	(r#"let inc = fun x -> x + 1 in inc 4"#, r#"5"#),
	(r#"let add = fun a b -> a + b in add 1 2"#, r#"3"#),
	(r#"add = lambda a, b=2: a + b; add(1)"#, r#"3"#),
	(r#"add = lambda a, b: a + b; add(1, 2)"#, r#"3"#),
	(r#"f = lambda *xs: sum(xs); f(1, 2, 3)"#, r#"6"#),
	(r#"const f = (...xs) => xs.length; f(1, 2)"#, r#"2"#),
	(r#"f = lambda: 42; f()"#, r#"42"#),
	(r#"f = lambda x: "big" if x > 2 else "small"; f(3)"#, r#"big"#),
	(r#"lambda = 3; lambda + 1"#, r#"4"#),
];

/// The value as `warp eval` shows it: a text without its quotes
fn shown(code: &str) -> String {
	let serialized = eval(code).serialize();
	serialized.strip_prefix('"').and_then(|text| text.strip_suffix('"')).map(str::to_string).unwrap_or(serialized)
}

#[test]
fn every_ported_call_form_keeps_its_value() {
	let failures: Vec<String> = CASES.iter().filter_map(|(code, want)| {
		let got = shown(code);
		(got != *want).then(|| format!("{code}\n  got {got}, want {want}"))
	}).collect();
	assert!(failures.is_empty(), "{} of {} forms changed:\n{}", failures.len(), CASES.len(), failures.join("\n"));
}

#[test]
fn linq_methods_work_with_a_note_naming_wasps_word() {
	// the alias rule (user 2026-10-06): a different word for the same meaning works and the note names wasp's word
	let (value, hints) = warp::normalize::capture_hints(|| shown("xs = [1, 2, 3]; xs.Select(x => x * 2).Where(x => x > 2)"));
	assert_eq!(value, "[4 6]");
	assert!(hints.iter().any(|hint| hint.canonical == ".map(" && hint.original == ".Select("), "{hints:?}");
}
