// WebIDL from w3c/webref (@webref/idl, generated by the specs), the definitions warp checks `use js` calls with
// (src/web_idl.rs): Clipboard, Crypto, EventTarget, GlobalPrivacyControl, Location, Navigator, NavigatorAutomationInformation, NavigatorBadge, NavigatorConcurrentHardware, NavigatorContentUtils, NavigatorCookies, NavigatorCrossOriginStorage, NavigatorDeviceMemory, NavigatorGPU, NavigatorID, NavigatorLanguage, NavigatorLocks, NavigatorML, NavigatorNetworkInformation, NavigatorOnLine, NavigatorPlugins, NavigatorStorage, NavigatorStorageBuckets, NavigatorUA, Performance, Storage, console whole; Window, WindowOrWorkerGlobalScope, WindowLocalStorage, WindowSessionStorage only with the globals of those.
// Each definition names the spec file it comes from.

// attribution.idl
partial interface Navigator {
  [SecureContext, SameObject] readonly attribute Attribution attribution;
};

// audio-session.idl
[Exposed=Window]
partial interface Navigator {
  readonly attribute AudioSession audioSession;
};

// autoplay-detection.idl
[Exposed=Window]
partial interface Navigator {
  AutoplayPolicy getAutoplayPolicy(AutoplayPolicyMediaType type);
  AutoplayPolicy getAutoplayPolicy(HTMLMediaElement element);
  AutoplayPolicy getAutoplayPolicy(AudioContext context);
};

// badging.idl
[SecureContext]
interface mixin NavigatorBadge {
  Promise<undefined> setAppBadge(
    optional [EnforceRange] unsigned long long contents
  );
  Promise<undefined> clearAppBadge();
};

// badging.idl
Navigator includes NavigatorBadge;

// battery-status.idl
[SecureContext]
partial interface Navigator {
  Promise<BatteryManager> getBattery();
};

// beacon.idl
partial interface Navigator {
    boolean sendBeacon(USVString url, optional BodyInit? data = null);
};

// bluetooth.idl
[SecureContext]
partial interface Navigator {
  [SameObject]
  readonly attribute Bluetooth bluetooth;
};

// clipboard-apis.idl
partial interface Navigator {
  [SecureContext, SameObject] readonly attribute Clipboard clipboard;
};

// clipboard-apis.idl
[SecureContext, Exposed=Window]
interface Clipboard : EventTarget {
  Promise<ClipboardItems> read(optional ClipboardUnsanitizedFormats formats = {});
  Promise<DOMString> readText();
  Promise<undefined> write(ClipboardItems data);
  Promise<undefined> writeText(DOMString data);
};

// console.idl
[Exposed=*]
namespace console { 
  undefined assert(optional boolean condition = false, any... data);
  undefined clear();
  undefined debug(any... data);
  undefined error(any... data);
  undefined info(any... data);
  undefined log(any... data);
  undefined table(optional any tabularData, optional sequence<DOMString> properties);
  undefined trace(any... data);
  undefined warn(any... data);
  undefined dir(optional any item, optional object? options);
  undefined dirxml(any... data);
  undefined count(optional DOMString label = "default");
  undefined countReset(optional DOMString label = "default");
  undefined group(any... data);
  undefined groupCollapsed(any... data);
  undefined groupEnd();
  undefined time(optional DOMString label = "default");
  undefined timeLog(optional DOMString label = "default", any... data);
  undefined timeEnd(optional DOMString label = "default");
};

// contact-picker.idl
[Exposed=Window]
partial interface Navigator {
  [SecureContext, SameObject] readonly attribute ContactsManager contacts;
};

// cpu-performance.idl
[
    SecureContext,
    Exposed=Window
] partial interface Navigator {
    readonly attribute unsigned short cpuPerformance;
};

// credential-management.idl
partial interface Navigator {
  [SecureContext, SameObject] readonly attribute CredentialsContainer credentials;
};

// cross-origin-storage.idl
interface mixin NavigatorCrossOriginStorage {
  [SameObject, SecureContext] readonly attribute CrossOriginStorageManager crossOriginStorage;
};

// cross-origin-storage.idl
Navigator includes NavigatorCrossOriginStorage;

// device-memory.idl
[
    SecureContext,
    Exposed=(Window,Worker)
] interface mixin NavigatorDeviceMemory {
    readonly attribute double deviceMemory;
};

// device-memory.idl
Navigator includes NavigatorDeviceMemory;

// device-posture.idl
[SecureContext, Exposed=(Window)]
partial interface Navigator {
  [SameObject] readonly attribute DevicePosture devicePosture;
};

// dom.idl
[Exposed=*]
interface EventTarget {
  constructor();
  undefined addEventListener(DOMString type, EventListener? callback, optional (AddEventListenerOptions or boolean) options = {});
  undefined removeEventListener(DOMString type, EventListener? callback, optional (EventListenerOptions or boolean) options = {});
  boolean dispatchEvent(Event event);
};

// encrypted-media.idl
[Exposed=Window]
partial interface Navigator {
  [SecureContext] Promise<MediaKeySystemAccess> requestMediaKeySystemAccess (
      DOMString keySystem,
      sequence<MediaKeySystemConfiguration> supportedConfigurations);
};

// event-timing.idl
[Exposed=Window]
partial interface Performance {
    [SameObject] readonly attribute EventCounts eventCounts;
    readonly attribute unsigned long long interactionCount;
};

// fenced-frame.idl
partial interface Navigator {
  Promise<undefined> deprecatedReplaceInURN(
    UrnOrConfig urnOrConfig, record<USVString, USVString> replacements);
  Promise<USVString> deprecatedURNtoURL(
    UrnOrConfig urnOrConfig, optional boolean send_reports = false);
  sequence<USVString> adAuctionComponents(unsigned short numAdComponents);
};

// gamepad.idl
[Exposed=Window]
partial interface Navigator {
  sequence<Gamepad?> getGamepads();
};

// geolocation.idl
partial interface Navigator {
  [SameObject] readonly attribute Geolocation geolocation;
};

// get-installed-related-apps.idl
[Exposed=Window]
partial interface Navigator {
  [SecureContext] Promise<sequence<RelatedApplication>> getInstalledRelatedApps();
};

// gpc.idl
interface mixin GlobalPrivacyControl {
  readonly attribute boolean globalPrivacyControl;
};

// gpc.idl
Navigator includes GlobalPrivacyControl;

// handwriting-recognition.idl
[SecureContext]
partial interface Navigator {
  Promise<HandwritingRecognizerQueryResult?>
      queryHandwritingRecognizer(HandwritingModelConstraint constraint);
};

// handwriting-recognition.idl
[SecureContext]
partial interface Navigator {
  Promise<HandwritingRecognizer>
      createHandwritingRecognizer(HandwritingModelConstraint constraint);
};

// hid.idl
[SecureContext] partial interface Navigator {
    [SameObject] readonly attribute HID hid;
};

// hr-time.idl
[Exposed=(Window,Worker)]
interface Performance : EventTarget {
    DOMHighResTimeStamp now();
    readonly attribute DOMHighResTimeStamp timeOrigin;
    [Default] object toJSON();
};

// hr-time.idl
partial interface mixin WindowOrWorkerGlobalScope {
  readonly attribute Performance performance;
};

// html.idl
partial interface Navigator {
  [SameObject] readonly attribute UserActivation userActivation;
};

// html.idl
partial interface Window {
  readonly attribute Location location;
  readonly attribute Navigator navigator;
  readonly attribute Navigator clientInformation;
};

// html.idl
[Exposed=Window]
interface Location { 
  [LegacyUnforgeable] stringifier attribute USVString href;
  [LegacyUnforgeable] readonly attribute USVString origin;
  [LegacyUnforgeable] attribute USVString protocol;
  [LegacyUnforgeable] attribute USVString host;
  [LegacyUnforgeable] attribute USVString hostname;
  [LegacyUnforgeable] attribute USVString port;
  [LegacyUnforgeable] attribute USVString pathname;
  [LegacyUnforgeable] attribute USVString search;
  [LegacyUnforgeable] attribute USVString hash;
  [LegacyUnforgeable] undefined assign(USVString url);
  [LegacyUnforgeable] undefined replace(USVString url);
  [LegacyUnforgeable] undefined reload();
  [LegacyUnforgeable] readonly attribute DOMStringList ancestorOrigins;
};

// html.idl
Window includes WindowOrWorkerGlobalScope;

// html.idl
[Exposed=Window]
interface Navigator {
};

// html.idl
Navigator includes NavigatorID;

// html.idl
Navigator includes NavigatorLanguage;

// html.idl
Navigator includes NavigatorOnLine;

// html.idl
Navigator includes NavigatorContentUtils;

// html.idl
Navigator includes NavigatorCookies;

// html.idl
Navigator includes NavigatorPlugins;

// html.idl
Navigator includes NavigatorConcurrentHardware;

// html.idl
interface mixin NavigatorID {
  readonly attribute DOMString appCodeName; 
  readonly attribute DOMString appName; 
  readonly attribute DOMString appVersion;
  readonly attribute DOMString platform;
  readonly attribute DOMString product; 
  [Exposed=Window] readonly attribute DOMString productSub;
  readonly attribute DOMString userAgent;
  [Exposed=Window] readonly attribute DOMString vendor;
  [Exposed=Window] readonly attribute DOMString vendorSub; 
};

// html.idl
partial interface mixin NavigatorID {
  [Exposed=Window] boolean taintEnabled(); 
  [Exposed=Window] readonly attribute DOMString oscpu;
};

// html.idl
interface mixin NavigatorLanguage {
  readonly attribute DOMString language;
  readonly attribute FrozenArray<DOMString> languages;
};

// html.idl
interface mixin NavigatorOnLine {
  readonly attribute boolean onLine;
};

// html.idl
interface mixin NavigatorContentUtils {
  [SecureContext] undefined registerProtocolHandler(DOMString scheme, USVString url);
  [SecureContext] undefined unregisterProtocolHandler(DOMString scheme, USVString url);
};

// html.idl
interface mixin NavigatorCookies {
  readonly attribute boolean cookieEnabled;
};

// html.idl
interface mixin NavigatorPlugins {
  [SameObject] readonly attribute PluginArray plugins;
  [SameObject] readonly attribute MimeTypeArray mimeTypes;
  boolean javaEnabled();
  readonly attribute boolean pdfViewerEnabled;
};

// html.idl
interface mixin NavigatorConcurrentHardware {
  readonly attribute unsigned long long hardwareConcurrency;
};

// html.idl
[Exposed=Window]
interface Storage {
  readonly attribute unsigned long length;
  DOMString? key(unsigned long index);
  getter DOMString? getItem(DOMString key);
  setter undefined setItem(DOMString key, DOMString value);
  deleter undefined removeItem(DOMString key);
  undefined clear();
};

// html.idl
partial interface mixin WindowSessionStorage {
  readonly attribute Storage sessionStorage;
};

// html.idl
Window includes WindowSessionStorage;

// html.idl
partial interface mixin WindowLocalStorage {
  readonly attribute Storage localStorage;
};

// html.idl
Window includes WindowLocalStorage;

// ink-enhancement.idl
[Exposed=Window]
partial interface Navigator {
    [SameObject] readonly attribute Ink ink;
};

// install-element.idl
partial interface Navigator {
  Promise<WebInstallResult> install();
  Promise<WebInstallResult> install(InstallParams options);
};

// is-input-pending.idl
partial interface Navigator {
  readonly attribute Scheduling scheduling;
};

// keyboard-lock.idl
partial interface Navigator {
  [SecureContext, SameObject] readonly attribute Keyboard keyboard;
};

// login-status.idl
partial interface Navigator {
  [SecureContext] readonly attribute NavigatorLogin login;
};

// managed-configuration.idl
[
  SecureContext
] partial interface Navigator {
  [SecureContext, SameObject]
  readonly attribute NavigatorManagedData managed;
};

// media-capabilities.idl
[Exposed=Window]
partial interface Navigator {
  [SameObject] readonly attribute MediaCapabilities mediaCapabilities;
};

// mediacapture-streams.idl
partial interface Navigator {
  [SameObject, SecureContext] readonly attribute MediaDevices mediaDevices;
};

// mediaqueries-5.idl
[Exposed=Window, SecureContext]
partial interface Navigator {
  [SameObject] readonly attribute PreferenceManager preferences;
};

// mediasession.idl
[Exposed=Window]
partial interface Navigator {
  [SameObject] readonly attribute MediaSession mediaSession;
};

// navigation-timing.idl
[Exposed=Window]
partial interface Performance {
  [SameObject]
  readonly attribute PerformanceTiming timing;
  [SameObject]
  readonly attribute PerformanceNavigation navigation;
};

// netinfo.idl
interface mixin NavigatorNetworkInformation {
  [SameObject] readonly attribute NetworkInformation connection;
};

// netinfo.idl
Navigator includes NavigatorNetworkInformation;

// observable.idl
partial interface EventTarget {
  Observable when(DOMString type, optional ObservableEventListenerOptions options = {});
};

// performance-measure-memory.idl
partial interface Performance {
  [Exposed=(Window,ServiceWorker,SharedWorker), CrossOriginIsolated] Promise<MemoryMeasurement> measureUserAgentSpecificMemory();
};

// performance-timeline.idl
partial interface Performance {
  PerformanceEntryList getEntries ();
  PerformanceEntryList getEntriesByType (DOMString type);
  PerformanceEntryList getEntriesByName (DOMString name, optional DOMString type);
};

// permissions.idl
[Exposed=(Window)]
partial interface Navigator {
  [SameObject] readonly attribute Permissions permissions;
};

// pointerevents.idl
partial interface Navigator {
    readonly  attribute long maxTouchPoints;
};

// presentation-api.idl
partial interface Navigator {
  [SecureContext, SameObject] readonly attribute Presentation presentation;
};

// resource-timing.idl
partial interface Performance {
      undefined clearResourceTimings ();
      undefined setResourceTimingBufferSize (unsigned long maxSize);
      attribute EventHandler onresourcetimingbufferfull;
    };

// screen-wake-lock.idl
[SecureContext]
partial interface Navigator {
  [SameObject] readonly attribute WakeLock wakeLock;
};

// serial.idl
[Exposed=Window, SecureContext]
partial interface Navigator {
  [SameObject] readonly attribute Serial serial;
};

// service-workers.idl
partial interface Navigator {
  [SecureContext, SameObject] readonly attribute ServiceWorkerContainer serviceWorker;
};

// storage-buckets.idl
[SecureContext]
interface mixin NavigatorStorageBuckets {
  [SameObject] readonly attribute StorageBucketManager storageBuckets;
};

// storage-buckets.idl
Navigator includes NavigatorStorageBuckets;

// storage.idl
[SecureContext]
interface mixin NavigatorStorage {
  [SameObject] readonly attribute StorageManager storage;
};

// storage.idl
Navigator includes NavigatorStorage;

// ua-client-hints.idl
interface mixin NavigatorUA {
  [SecureContext] readonly attribute NavigatorUAData userAgentData;
};

// ua-client-hints.idl
Navigator includes NavigatorUA;

// usb.idl
[Exposed=Window, SecureContext]
partial interface Navigator {
  [SameObject] readonly attribute USB usb;
};

// user-timing.idl
partial interface Performance {
    PerformanceMark mark(DOMString markName, optional PerformanceMarkOptions markOptions = {});
    undefined clearMarks(optional DOMString markName);
    PerformanceMeasure measure(DOMString measureName, optional (DOMString or PerformanceMeasureOptions) startOrMeasureOptions = {}, optional DOMString endMark);
    undefined clearMeasures(optional DOMString measureName);
};

// vibration.idl
partial interface Navigator {
    boolean vibrate (VibratePattern pattern);
};

// virtual-keyboard.idl
partial interface Navigator {
    [SecureContext, SameObject] readonly attribute VirtualKeyboard virtualKeyboard;
};

// web-locks.idl
[SecureContext]
interface mixin NavigatorLocks {
  readonly attribute LockManager locks;
};

// web-locks.idl
Navigator includes NavigatorLocks;

// web-share.idl
partial interface Navigator {
  [SecureContext] Promise<undefined> share(optional ShareData data = {});
  [SecureContext] boolean canShare(optional ShareData data = {});
};

// webcrypto.idl
partial interface mixin WindowOrWorkerGlobalScope {
  readonly attribute Crypto crypto;
};

// webcrypto.idl
[Exposed=(Window,Worker)]
interface Crypto {
  [SecureContext] readonly attribute SubtleCrypto subtle;
  ArrayBufferView getRandomValues(ArrayBufferView array);
  [SecureContext] DOMString randomUUID();
};

// webdriver.idl
interface mixin NavigatorAutomationInformation {
  readonly attribute boolean webdriver;
};

// webdriver.idl
Navigator includes NavigatorAutomationInformation;

// webgpu.idl
interface mixin NavigatorGPU {
    [SameObject, SecureContext] readonly attribute GPU gpu;
};

// webgpu.idl
Navigator includes NavigatorGPU;

// webmidi.idl
partial interface Navigator {
  [SecureContext]
  Promise <MIDIAccess> requestMIDIAccess(optional MIDIOptions options = {});
};

// webnn.idl
interface mixin NavigatorML {
  [SecureContext, SameObject] readonly attribute ML ml;
};

// webnn.idl
Navigator includes NavigatorML;

// webxr.idl
partial interface Navigator {
  [SecureContext, SameObject] readonly attribute XRSystem xr;
};

// window-controls-overlay.idl
[SecureContext, Exposed=(Window)]
partial interface Navigator {
  [SameObject] readonly attribute WindowControlsOverlay windowControlsOverlay;
};

