"""Bundles WebIDL from webref's idl files (npm pack @webref/idl) into lib/web.webidl:
python3 scripts/webidl_bundle.py <package dir> console,Crypto,Performance,Storage,Navigator,Location,Clipboard,WorkerNavigator,WorkerLocation,Document,Element,NodeList,HTMLCollection,DOMTokenList,Event,WindowOrWorkerGlobalScope,Response,Headers,URL,URLSearchParams,Blob,WebSocket,$(grep -oE "^interface HTML[A-Za-z]*Element" <package dir>/html.idl | cut -d" " -f2 | sort -u | paste -sd, -) Window,WindowOrWorkerGlobalScope,WindowLocalStorage,WindowSessionStorage,WorkerGlobalScope > lib/web.webidl
Checked interfaces come whole: every partial, every mixin they include and every parent, from all files. A global scope
(Window and its mixins) comes only with its attributes whose type is a checked interface: the names of the globals."""
import glob, os, re, sys

HEADER = re.compile(r"^(?:\[[^\]]*\]\s*)?(partial\s+)?(interface\s+mixin|interface|namespace|dictionary|enum|typedef|callback\s+interface|callback)\s+(\w+)\s*(?::\s*(\w+))?")
INCLUDES = re.compile(r"^(\w+)\s+includes\s+(\w+)\s*;$")
ATTRIBUTE = re.compile(r"attribute\s+(\w+)\??\s+(\w+)\s*;")

def definitions(text):
    """each top-level definition: its source, without comments and blank lines"""
    text = re.sub(r"//[^\n]*|/\*.*?\*/", "", text, flags=re.S)
    depth, start = 0, 0
    for at, c in enumerate(text):
        if c in "{[(": depth += 1
        elif c in "}])": depth -= 1
        elif c == ";" and depth == 0:
            yield re.sub(r"\n\s*\n", "\n", text[start:at + 1].strip())
            start = at + 1

directory, checked, scopes = sys.argv[1], set(sys.argv[2].split(",")), sys.argv[3].split(",")
parsed = []  # (file, kind, name, parent, source) or (file, "includes", target, mixin, source)
for path in sorted(glob.glob(f"{directory}/*.idl")):
    file = os.path.basename(path)
    for source in definitions(open(path).read()):
        if match := INCLUDES.match(source):
            parsed.append((file, "includes", match[1], match[2], source))
        elif match := HEADER.match(source):
            parsed.append((file, match[2], match[3], match[4], source))

while True:  # the closure: mixins and parents of what is checked
    more = {mixin for _, kind, name, mixin, _ in parsed if kind == "includes" and name in checked}
    more |= {parent for _, kind, name, parent, _ in parsed if kind != "includes" and name in checked and parent}
    if more <= checked: break
    checked |= more

print("// WebIDL from w3c/webref (@webref/idl, generated by the specs), the definitions warp checks `use js` calls with")
print("// (src/web_idl.rs): " + ", ".join(sorted(checked)) + " whole; " + ", ".join(scopes) + " only with the globals of those.")
print("// Each definition names the spec file it comes from.\n")
for file, kind, name, other, source in parsed:
    if kind == "includes":
        keep = name in checked or (name in scopes and (other in checked or other in scopes))
    elif name in checked:
        keep = kind not in ("dictionary", "enum", "typedef", "callback")
    elif name in scopes and kind != "includes":
        globals = [f"  readonly attribute {type} {attribute};" for type, attribute in ATTRIBUTE.findall(source) if type in checked]
        if not globals: continue
        mixin = " mixin" if "mixin" in kind else ""
        source = f"partial interface{mixin} {name} {{\n" + "\n".join(globals) + "\n};"
        keep = True
    else:
        keep = False
    if keep: print(f"// {file}\n{source}\n")
