//! Uniscript entities (wiki/uniscript.md, unicode.md, Features.md; user decision P56): `\:infinity` and `\:alpha` are the
//! characters ∞ and α, as identifiers and operators alike (`\:alpha = 4` assigns α), and inside double-quoted texts
//! (the text parser expands them there). A bare `\name` is no entity (`"\nat"` is a newline and "at"). The names are
//! those of the uniscript package's index that `\:name` can spell; the `<:fracture A>` blocks are the package itself.

use std::collections::HashMap;
use std::sync::OnceLock;

/// `name\tcharacters` lines: the single-word names of the pinned uniscript's data/entities.idx (packages.wasp),
/// generated by tests/parser/test_entity_table.rs, which also checks it against the pin
const ENTITIES: &str = include_str!("uniscript_entities.tsv");

/// The characters an entity name stands for
pub fn entity(name: &str) -> Option<&'static str> {
	static TABLE: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
	TABLE.get_or_init(|| ENTITIES.lines().filter_map(|line| line.split_once('\t')).collect()).get(name).copied()
}

/// The entity written at `chars[at..]`, `\:name` (the name its whole run of ASCII letters): its name and the number of
/// chars it spans
pub fn entity_name_at(chars: &[char], at: usize) -> Option<(String, usize)> {
	if chars.get(at) != Some(&'\\') || chars.get(at + 1) != Some(&':') {
		return None;
	}
	let name: String = chars[at + 2..].iter().take_while(|c| c.is_ascii_alphabetic()).collect();
	(!name.is_empty()).then(|| (name.clone(), 2 + name.len()))
}

/// `\alpha` written for `\:alpha`: the name of the entity a bare backslash name would be
pub fn bare_entity_name_at(chars: &[char], at: usize) -> Option<String> {
	if chars.get(at) != Some(&'\\') {
		return None;
	}
	let name: String = chars[at + 1..].iter().take_while(|c| c.is_ascii_alphabetic()).collect();
	entity(&name).map(|_| name)
}

/// The warning of `\:name` that names no entity: it stays as written (card unknown-entity)
pub fn unknown_entity(name: &str) -> String {
	format!("unknown entity \\:{name} stays as written: write the character itself, or a known name such as \\:alpha or \\:infinity")
}

/// The source with every known entity outside texts and comments replaced by its character; an unknown one stays
/// and the parser warns about it (texts expand theirs in the text parser)
pub fn expand_entities(source: &str) -> String {
	if !source.contains('\\') {
		return source.to_string();
	}
	let chars: Vec<char> = source.chars().collect();
	let mut expanded = String::with_capacity(source.len());
	let mut at = 0;
	while at < chars.len() {
		if let Some(end) = crate::wasp_parser::text_or_comment_end(&chars, at) {
			expanded.extend(&chars[at..end]);
			at = end;
			continue;
		}
		match entity_name_at(&chars, at).and_then(|(name, length)| Some((entity(&name)?, length))) {
			Some((characters, length)) => {
				expanded.push_str(characters);
				at += length;
			}
			None => {
				expanded.push(chars[at]);
				at += 1;
			}
		}
	}
	expanded
}
